allowBuilds:
  esbuild: true
  protobufjs: true

minimumReleaseAgeExclude:
  - tsx@4.22.2

publicHoistPattern:
  - 'playwright*'
  - 'bson'
  - 'framer-motion*'
  - '@tf2pickup-org/*'
  - '@discordjs/*'
  - 'discord-api-types'
  - 'helmet'
  - '@fastify/*'
  - '@opentelemetry/*'
  - 'thread-stream'
