import './htmx'
import 'htmx.org/dist/ext/head-support.js'
import 'htmx.org/dist/ext/ws.js'
import 'htmx.org/dist/ext/remove-me.js'
import 'https://unpkg.com/hyperscript.org@0.9.13/dist/_hyperscript.min.js'
import './idiomorph.ts'

import './countdown'
import './disable-when-offline'
import './fade-scroll'
import './flash-message'
import './map-thumbnail'
import './notification'

export { goTo } from './navigation'
